# 1. PUERTO DINÁMICO
# Render inyectará su propio puerto en la variable ${PORT}. 
# Si estás en tu PC (localhost), usará el 8080 por defecto.
server.port=${PORT:8080}

# 2. CONEXIÓN A LA BASE DE DATOS (Segura)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

# 3. CONFIGURACIÓN DE HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true